import{bulkPrompt,makeSlideZip,makeZip,n,parseJson,pretty,readiness,slidePrompt,slug}from'./prompting.js';
import{makeSlide,parseStorySets}from'./parser.js';

const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const steps=['Copy','Review Story','Assets & References','Generate'];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const asset=f=>f?{id:`asset-${crypto.randomUUID()}`,file:f,filename:f.name,type:f.type||'application/octet-stream'}:null;
const stripFile=a=>a&&({id:a.id,filename:a.filename,type:a.type});
const defaultSet=()=>({id:`set-${crypto.randomUUID()}`,title:'Untitled Story Set',rawStorySetCopy:'',parseStatus:'confirmed',parseWarnings:[],overallDirection:'',slides:[makeSlide(1)],mainAssets:[],references:[],logo:null});
const stored=JSON.parse(localStorage.getItem('ladytin-json-studio')||'{}');
function migrate(x){
  if(Array.isArray(x.storySets)&&x.storySets.length)return x.storySets.map(normaliseSet);
  if(Array.isArray(x.slides))return[normaliseSet({id:`set-${crypto.randomUUID()}`,title:x.title||'Untitled Story Set',rawStorySetCopy:x.copyDraft||'',slides:x.slides,overallDirection:x.overallDirection||'',mainAssets:[],references:[],logo:x.logo})];
  return[defaultSet()];
}
function normaliseSlide(s,i){return{...makeSlide(i+1),...s,slide_number:i+1,overlay_text:s.overlay_text??s.copy??'',copy:s.overlay_text??s.copy??'',direction:s.direction??s.art??'',art:s.direction??s.art??'',main:s.main||null,reference:s.reference||null}}
function normaliseSet(s){return{...defaultSet(),...s,bp:undefined,defaultRef:undefined,slides:(s.slides?.length?s.slides:[makeSlide(1)]).map(normaliseSlide),mainAssets:s.mainAssets||[],references:s.references||[],overallDirection:s.overallDirection||''}}
const state={storySets:migrate(stored),activeSet:stored.activeSet||0,activeStep:Math.min(stored.activeStep||0,3),rawInput:stored.rawInput||stored.copyDraft||'',parseReview:null,selectedSlide:stored.selectedSlide||0};
state.activeSet=Math.min(state.activeSet,state.storySets.length-1);
let toastTimer;

function current(){return state.storySets[state.activeSet]}
function save(){
  const sets=state.storySets.map(set=>({...set,bp:undefined,defaultRef:undefined,mainAssets:set.mainAssets.map(stripFile),references:set.references.map(stripFile),logo:stripFile(set.logo),slides:set.slides.map(s=>({...s,main:stripFile(s.main),reference:stripFile(s.reference)}))}));
  localStorage.setItem('ladytin-json-studio',JSON.stringify({storySets:sets,activeSet:state.activeSet,activeStep:state.activeStep,selectedSlide:state.selectedSlide,rawInput:state.rawInput}));
}
function toast(text,tone='ok'){const el=$('#toast');if(!el)return;el.textContent=text;el.className=`toast show ${tone}`;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.className='toast',2800)}
async function cp(text,message='JSON copied.'){await navigator.clipboard?.writeText(text);toast(message)}
function dl(name,data,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(data instanceof Blob?data:new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1200)}
const badge=(text,tone='')=>`<span class="badge ${tone}">${esc(text)}</span>`;
const btn=(text,id,kind='secondary',attrs='')=>`<button class="btn ${kind}" id="${id}" ${attrs}>${text}</button>`;
const field=(label,control,help='')=>`<label class="field"><span>${label}</span>${control}${help?`<small>${help}</small>`:''}</label>`;
function preview(a){if(!a)return'<div class="file-tile empty">No file</div>';if(a.type?.startsWith('image/')&&a.file)return`<img class="thumb" src="${URL.createObjectURL(a.file)}" alt="">`;if(a.type?.startsWith('video/'))return'<div class="file-tile">VIDEO</div>';if(a.type==='application/pdf')return'<div class="file-tile">PDF</div>';return'<div class="file-tile">FILE</div>'}
function fullJson(){return pretty(bulkPrompt(current().slides,current(),current().logo))}
function rows(){return readiness(current().slides,current(),current().logo)}
function setStep(i){state.activeStep=Math.max(0,Math.min(3,i));save();render();scrollTo({top:0,behavior:'smooth'})}
function progress(){const set=current(),r=rows();return[!!state.rawInput.trim()||set.slides.some(s=>(s.copy||'').trim()),set.parseStatus==='confirmed'&&set.slides.length>0,set.slides.every(s=>s.main&&s.reference),r.every(x=>x.ready)]}

function shell(content,title,desc){
  const done=progress(),set=current();
  return`<div class="app-shell"><header class="topbar"><div><b>LadyTin Story Studio</b><span class="project-status">${esc(set.title)}</span></div><div class="top-actions"><select id="setPicker" aria-label="Active story set">${state.storySets.map((s,i)=>`<option value="${i}" ${i===state.activeSet?'selected':''}>${String(i+1).padStart(2,'0')} · ${esc(s.title)}</option>`).join('')}</select>${btn('Save Project','saveProject')}${state.activeStep<3?btn('Continue','continue','primary'):''}</div></header><nav class="stepper" aria-label="Workflow">${steps.map((s,i)=>`<button class="step ${i===state.activeStep?'active':''} ${done[i]?'done':''}" data-step="${i}"><span>${String(i+1).padStart(2,'0')}</span>${s}</button>`).join('')}</nav><main class="page"><div class="page-head"><div><div class="eyebrow">${String(state.activeStep+1).padStart(2,'0')} / 04</div><h1>${title}</h1><p>${desc}</p></div></div>${content}</main><div id="toast" class="toast" role="status" aria-live="polite"></div></div>`
}

function copyPage(){
  if(state.parseReview)return reviewParsedPage();
  const placeholder=`SET 2 — The Journey of a Garment\n\nSlide 1 — It starts on a wall covered in paper. Everything still possible.\n\nSlide 2 — Then it reaches hands in India. Hands that have been stitching this way for generations.\n\nSlide 3 — The smallest details are always added last. That is where everything comes together.\n\nSlide 4 — What reaches you is not just one garment.\nCTA: See where it begins.`;
  return shell(`<div class="copy-layout"><section class="panel">${field('Paste Complete Story Set Copy',`<textarea id="rawInput" class="copy-editor" placeholder="${esc(placeholder)}">${esc(state.rawInput)}</textarea>`,'Paste one complete set or several SET blocks together. Exact wording is preserved.')}<div class="action-row">${btn('Parse Story Set','parse','primary')}${btn('Insert Slide Break','insertBreak','tertiary')}${btn('Save Draft','saveDraft')}${btn('Clear','clear','tertiary')}</div></section><aside class="panel guidance"><h2>Parser recognises</h2><p>Set titles, slide markers, CTA, Poll, Question, Direction, video/content descriptions, no-text-overlay and caption-CC instructions.</p><ul><li>Copy is never rewritten.</li><li>Several sets can be pasted together.</li><li>Nothing replaces project data until confirmation.</li></ul></aside></div>`,'Copy','Paste the complete story-set copy once, then review the detected structure.')
}

function reviewParsedPage(){
  const review=state.parseReview,active=review.active??0,set=review.sets[active];
  return shell(`<div class="review-layout"><aside class="panel review-summary"><div class="panel-head"><h2>${review.sets.length} set${review.sets.length===1?'':'s'} detected</h2>${badge(`${review.totalSlides} slides`)}</div>${review.sets.map((s,i)=>`<button class="review-set ${i===active?'active':''} ${s.included===false?'excluded':''}" data-review-set="${i}"><b>${esc(s.title)}</b><small>${s.slides.length} slides · ${s.parseWarnings.length} warnings</small></button>`).join('')}<div class="stack-actions">${btn('Confirm All Included Sets','confirmParsed','primary')}${btn('Re-parse','reparse')}${btn('Return to Raw Copy','backRaw','tertiary')}${btn('Cancel','cancelParse','danger')}</div></aside><section class="panel"><div class="panel-head"><div><div class="eyebrow">Review Parsed Story Set</div><h2>${esc(set.title)}</h2></div><label class="include-check"><input type="checkbox" id="includeSet" ${set.included===false?'':'checked'}> Include set</label></div>${field('Detected set title',`<input id="reviewTitle" value="${esc(set.title)}">`)}${set.parseWarnings.length?`<div class="warning-box">${set.parseWarnings.map(w=>`<p>• ${esc(w)}</p>`).join('')}</div>`:''}<div class="parsed-list">${set.slides.map((s,i)=>`<article class="parsed-row"><div class="parsed-number">${n(i)}</div><div>${field('Exact overlay copy',`<textarea data-review-slide="${i}" data-key="overlay_text">${esc(s.overlay_text)}</textarea>`)}<div class="form-grid">${field('CTA',`<input data-review-slide="${i}" data-key="cta" value="${esc(s.cta)}">`)}${field('Interaction',`<input data-review-slide="${i}" data-key="interaction" value="${esc(s.interaction)}">`)}</div>${field('Content / video description',`<input data-review-slide="${i}" data-key="content_description" value="${esc(s.content_description)}">`)}${field('Direction',`<textarea data-review-slide="${i}" data-key="direction">${esc(s.direction)}</textarea>`)}<div class="check-row"><label><input type="checkbox" data-review-check="${i}" data-key="no_text_overlay" ${s.no_text_overlay?'checked':''}> No text overlay</label><label><input type="checkbox" data-review-check="${i}" data-key="caption_cc" ${s.caption_cc?'checked':''}> Caption CC</label></div></div></article>`).join('')}</div></section></div>`,'Review Parsed Story Set','Check the parser result and correct individual fields before creating project data.')
}

function reviewStoryPage(){
  const set=current(),i=Math.min(state.selectedSlide,set.slides.length-1),s=set.slides[i];
  return shell(`<div class="set-strip panel"><div><b>${esc(set.title)}</b><small>${set.slides.length} slides · ${set.parseStatus}</small></div>${btn('Re-parse From Original Copy','reparseOriginal','tertiary')}</div><div class="master-detail"><aside class="panel story-list"><div class="panel-head"><h2>Slides</h2>${btn('+ Slide','addSlide','tertiary')}</div>${set.slides.map((x,j)=>`<button class="story-item ${j===i?'active':''}" data-slide="${j}"><span>${n(j)}</span><div><b>${esc((x.copy||x.content_description||`Slide ${j+1}`).slice(0,46))}</b><small>${esc(x.role||'Unassigned')}</small></div></button>`).join('')}</aside><section class="panel detail">${field('Story-set title',`<input id="setTitle" value="${esc(set.title)}">`)}${field('Overall Set Direction — Optional',`<textarea id="overallDirection" placeholder="Keep the complete set soft, tactile and intimate. Use one restrained recurring motif.">${esc(set.overallDirection)}</textarea>`,'This replaces the former Set Direction stage and is included in every prompt.')}<div class="panel-head"><div><div class="eyebrow">Slide ${n(i)}</div><h2>${esc(s.role)}</h2></div><div class="mini-actions">${i>0?btn('Move Up','moveUp','tertiary'):''}${i<set.slides.length-1?btn('Move Down','moveDown','tertiary'):''}${set.slides.length>1?btn('Remove','removeSlide','danger'):''}</div></div><div class="form-grid">${field('Role in story arc',`<select data-slide-field="role"><option>Opening</option><option>Development</option><option>Engagement</option><option>Resolution / CTA</option></select>`)}${field('CTA',`<input data-slide-field="cta" value="${esc(s.cta)}">`)}</div>${field('Exact overlay copy',`<textarea data-slide-field="copy">${esc(s.copy)}</textarea>`)}${field('Interaction',`<input data-slide-field="interaction" value="${esc(s.interaction)}">`)}${field('Content / video direction',`<input data-slide-field="content_description" value="${esc(s.content_description)}">`)}${field('Slide-specific direction — Optional',`<textarea data-slide-field="direction">${esc(s.direction)}</textarea>`)}<div class="check-row"><label><input type="checkbox" data-slide-check="no_text_overlay" ${s.no_text_overlay?'checked':''}> No text overlay</label><label><input type="checkbox" data-slide-check="caption_cc" ${s.caption_cc?'checked':''}> Caption CC</label></div></section></div>`,'Review Story','Review the confirmed copy, story arc, order and optional directions.')
}

function uploadBox(id,title,accept,multiple=true){return`<label class="upload-box"><b>${title}</b><small>${accept}</small><input id="${id}" type="file" accept="${accept}" ${multiple?'multiple':''}></label>`}
function library(title,items,type){
  return`<section class="panel library"><div class="panel-head"><h2>${title}</h2>${badge(`${items.length} files`)}</div><div class="library-grid">${items.length?items.map(a=>{const count=current().slides.filter(s=>(type==='main'?s.main?.id:s.reference?.id)===a.id).length;return`<article class="library-card">${preview(a)}<div><b title="${esc(a.filename)}">${esc(a.filename)}</b><small>${esc(a.type)} · ${count} slide${count===1?'':'s'}</small></div><button class="icon-btn" data-remove-library="${type}:${a.id}" aria-label="Remove ${esc(a.filename)}">×</button></article>`}).join(''):'<p class="empty-copy">No files uploaded yet.</p>'}</div>${type==='ref'&&items.length?`<div class="apply-row"><select id="applyReference"><option value="">Select reference…</option>${items.map(a=>`<option value="${a.id}">${esc(a.filename)}</option>`).join('')}</select>${btn('Apply to All Unassigned Slides','applyRef','tertiary')}</div>`:''}</section>`
}
function assetsPage(){
  const set=current();
  return shell(`<div class="upload-workspace panel"><div>${uploadBox('uploadMain','Upload Main Assets','image/jpeg,image/png,image/webp,image/heic,image/gif,video/mp4,video/quicktime,video/x-m4v')}</div><div>${uploadBox('uploadRefs','Upload Design References','image/jpeg,image/png,image/webp,application/pdf')}</div></div><div class="libraries">${library('Main Asset Library',set.mainAssets,'main')}${library('Design Reference Library',set.references,'ref')}</div><section class="assignments"><div class="section-title"><h2>Slide Assignments</h2><p>Assign the source image and design reference for every slide.</p></div>${set.slides.map((s,i)=>`<article class="assignment"><div class="assignment-head"><div><div class="eyebrow">Slide ${n(i)} · ${esc(s.role)}</div><b>${esc((s.copy||s.content_description||'No visible copy').slice(0,105))}</b></div>${s.main&&s.reference?badge('Ready','ok'):badge('Incomplete','bad')}</div><div class="assignment-grid"><div>${field('Main asset',`<select data-assign-main="${i}"><option value="">Select main asset…</option>${set.mainAssets.map(a=>`<option value="${a.id}" ${s.main?.id===a.id?'selected':''}>${esc(a.filename)}</option>`).join('')}</select>`)}${preview(s.main)}</div><div>${field('Design reference',`<select data-assign-ref="${i}"><option value="">Select reference…</option>${set.references.map(a=>`<option value="${a.id}" ${s.reference?.id===a.id?'selected':''}>${esc(a.filename)}</option>`).join('')}</select>`)}${preview(s.reference)}</div><div>${field('Slide-specific direction — Optional',`<textarea data-assignment-direction="${i}">${esc(s.direction)}</textarea>`)}</div></div></article>`).join('')}</section>`,'Assets & References','Assign the source image and design reference for every slide.')
}

function generatePage(){
  const set=current(),r=rows(),ready=r.every(x=>x.ready),full=fullJson();
  return shell(`<section class="panel"><div class="panel-head"><div><h2>Story-set readiness</h2><p>${r.filter(x=>x.ready).length} of ${r.length} slides ready</p></div>${ready?badge('Ready','ok'):badge('Blocked','bad')}</div><div class="table-wrap"><table><thead><tr><th>Slide</th><th>Main Asset</th><th>Reference</th><th>JSON</th><th>Ready</th></tr></thead><tbody>${r.map(x=>`<tr><td>${n(x.slide-1)}</td><td>${x.main?'Ready':'Missing'}</td><td>${x.reference?'Ready':'Missing'}</td><td>${x.json?'Valid':'Invalid'}</td><td>${x.ready?badge('Ready','ok'):`<span class="missing">${esc(x.missing.join(', '))}</span>`}</td></tr>`).join('')}</tbody></table></div></section><section class="panel bulk-panel"><div><div class="eyebrow">Complete story set</div><h2>${esc(set.title)}</h2><p>${set.slides.length} slides · JSON ${parseJson(full).ok?'valid':'invalid'}</p></div><div class="bulk-actions">${btn('Copy Full Story-Set JSON','copyFull','primary')}${btn('Download Full Story-Set JSON','downloadFull')}${btn('Download Full Story-Set ZIP','downloadZip','primary',ready?'':'disabled')}${btn('Download Incomplete Draft Package','downloadDraft','tertiary')}</div></section><div class="section-title"><h2>Individual slides</h2><p>JSON is hidden until requested.</p></div><div class="production-grid">${set.slides.map((s,i)=>{const x=r[i],json=pretty(slidePrompt(s,i,set.slides,set,set.logo));return`<article class="production-card"><div class="card-top"><div><div class="eyebrow">Slide ${n(i)}</div><b>${esc(s.role)}</b></div>${x.ready?badge('Ready','ok'):badge('Blocked','bad')}</div><div class="preview-pair"><div>${preview(s.main)}<small>Source</small></div><div>${preview(s.reference)}<small>Reference</small></div></div><p class="copy-excerpt">${esc(s.copy||s.content_description||'No visible overlay copy')}</p><div class="card-actions"><button class="btn tertiary" data-action="copy" data-i="${i}">Copy Slide JSON</button><button class="btn tertiary" data-action="json" data-i="${i}">Download Slide JSON</button><button class="btn tertiary" data-action="package" data-i="${i}">Download Slide Package</button><button class="btn tertiary" data-action="validate" data-i="${i}">Validate</button><button class="btn tertiary" data-action="view" data-i="${i}">View JSON</button></div><details id="json-${i}" class="json-panel"><summary>Slide JSON</summary><pre>${esc(json)}</pre></details></article>`}).join('')}</div>`,'Generate','Validate and export individual slides or the complete story set.')
}

function render(){const views=[copyPage,reviewStoryPage,assetsPage,generatePage];$('#root').innerHTML=views[state.activeStep]();wire()}
function parseNow(){if(!state.rawInput.trim())return toast('Paste complete story-set copy first.','bad');const result=parseStorySets(state.rawInput);state.parseReview={...result,active:0};render()}
function confirmReview(){const sets=state.parseReview.sets.filter(s=>s.included!==false).map(normaliseSet);if(!sets.length)return toast('Include at least one story set.','bad');sets.forEach(s=>s.parseStatus='confirmed');state.storySets=sets;state.activeSet=0;state.selectedSlide=0;state.parseReview=null;state.activeStep=1;save();render();toast(`${sets.length} story set${sets.length===1?'':'s'} created.`)}

function wire(){
  $('#saveProject')?.addEventListener('click',()=>{save();toast('Project saved.')});
  $('#continue')?.addEventListener('click',()=>setStep(state.activeStep+1));
  $('#setPicker')?.addEventListener('change',e=>{state.activeSet=+e.target.value;state.selectedSlide=0;save();render()});
  $$('[data-step]').forEach(b=>b.onclick=()=>setStep(+b.dataset.step));
  $('#rawInput')?.addEventListener('input',e=>{state.rawInput=e.target.value;save()});
  $('#parse')?.addEventListener('click',parseNow);
  $('#insertBreak')?.addEventListener('click',()=>{const t=$('#rawInput'),start=t.selectionStart;state.rawInput=state.rawInput.slice(0,start)+'\n\nSLIDE BREAK\n\n'+state.rawInput.slice(t.selectionEnd);render()});
  $('#saveDraft')?.addEventListener('click',()=>{save();toast('Draft saved.')});
  $('#clear')?.addEventListener('click',()=>{state.rawInput='';save();render()});
  $$('[data-review-set]').forEach(b=>b.onclick=()=>{state.parseReview.active=+b.dataset.reviewSet;render()});
  $('#includeSet')?.addEventListener('change',e=>{state.parseReview.sets[state.parseReview.active].included=e.target.checked;render()});
  $('#reviewTitle')?.addEventListener('input',e=>state.parseReview.sets[state.parseReview.active].title=e.target.value);
  $$('[data-review-slide]').forEach(el=>el.oninput=e=>{const s=state.parseReview.sets[state.parseReview.active].slides[+el.dataset.reviewSlide];s[el.dataset.key]=e.target.value;if(el.dataset.key==='overlay_text')s.copy=e.target.value;if(el.dataset.key==='direction')s.art=e.target.value});
  $$('[data-review-check]').forEach(el=>el.onchange=e=>state.parseReview.sets[state.parseReview.active].slides[+el.dataset.reviewCheck][el.dataset.key]=e.target.checked);
  $('#confirmParsed')?.addEventListener('click',confirmReview);
  $('#reparse')?.addEventListener('click',parseNow);
  $('#backRaw')?.addEventListener('click',()=>{state.parseReview=null;render()});
  $('#cancelParse')?.addEventListener('click',()=>{state.parseReview=null;render()});
  $('#setTitle')?.addEventListener('input',e=>{current().title=e.target.value;save()});
  $('#overallDirection')?.addEventListener('input',e=>{current().overallDirection=e.target.value;save()});
  $('#reparseOriginal')?.addEventListener('click',()=>{if(confirm('Re-parsing may replace manual copy edits. Continue?')){state.rawInput=current().rawStorySetCopy||state.rawInput;state.activeStep=0;parseNow()}});
  $$('[data-slide]').forEach(b=>b.onclick=()=>{state.selectedSlide=+b.dataset.slide;render()});
  $('[data-slide-field="role"]')&&( $('[data-slide-field="role"]').value=current().slides[state.selectedSlide].role );
  $$('[data-slide-field]').forEach(el=>el.oninput=e=>{const s=current().slides[state.selectedSlide],k=el.dataset.slideField;s[k]=e.target.value;if(k==='copy')s.overlay_text=e.target.value;if(k==='direction')s.art=e.target.value;save()});
  $$('[data-slide-check]').forEach(el=>el.onchange=e=>{current().slides[state.selectedSlide][el.dataset.slideCheck]=e.target.checked;save()});
  $('#addSlide')?.addEventListener('click',()=>{current().slides.push(makeSlide(current().slides.length+1));state.selectedSlide=current().slides.length-1;save();render()});
  $('#removeSlide')?.addEventListener('click',()=>{current().slides.splice(state.selectedSlide,1);current().slides.forEach((s,i)=>s.slide_number=i+1);state.selectedSlide=Math.max(0,state.selectedSlide-1);save();render()});
  $('#moveUp')?.addEventListener('click',()=>{const a=current().slides,i=state.selectedSlide;[a[i-1],a[i]]=[a[i],a[i-1]];state.selectedSlide--;a.forEach((s,j)=>s.slide_number=j+1);save();render()});
  $('#moveDown')?.addEventListener('click',()=>{const a=current().slides,i=state.selectedSlide;[a[i+1],a[i]]=[a[i],a[i+1]];state.selectedSlide++;a.forEach((s,j)=>s.slide_number=j+1);save();render()});
  const addFiles=(input,key)=>input?.addEventListener('change',e=>{for(const f of e.target.files)current()[key].push(asset(f));save();render();toast(`${e.target.files.length} file${e.target.files.length===1?'':'s'} uploaded.`)});
  addFiles($('#uploadMain'),'mainAssets');addFiles($('#uploadRefs'),'references');
  $$('[data-remove-library]').forEach(b=>b.onclick=()=>{const[type,id]=b.dataset.removeLibrary.split(':'),key=type==='main'?'mainAssets':'references';current()[key]=current()[key].filter(a=>a.id!==id);current().slides.forEach(s=>{if(type==='main'&&s.main?.id===id)s.main=null;if(type==='ref'&&s.reference?.id===id)s.reference=null});save();render()});
  $$('[data-assign-main]').forEach(el=>el.onchange=e=>{const i=+el.dataset.assignMain;current().slides[i].main=current().mainAssets.find(a=>a.id===e.target.value)||null;current().slides[i].assetId=e.target.value;save();render()});
  $$('[data-assign-ref]').forEach(el=>el.onchange=e=>{const i=+el.dataset.assignRef;current().slides[i].reference=current().references.find(a=>a.id===e.target.value)||null;current().slides[i].referenceId=e.target.value;save();render()});
  $$('[data-assignment-direction]').forEach(el=>el.oninput=e=>{const s=current().slides[+el.dataset.assignmentDirection];s.direction=e.target.value;s.art=e.target.value;save()});
  $('#applyRef')?.addEventListener('click',()=>{const id=$('#applyReference').value;if(!id)return toast('Select a reference first.','bad');const ref=current().references.find(a=>a.id===id);let count=0;current().slides.forEach(s=>{if(!s.reference){s.reference=ref;s.referenceId=id;count++}});save();render();toast(`Reference applied to ${count} unassigned slide${count===1?'':'s'}.`)});
  $('#copyFull')?.addEventListener('click',()=>cp(fullJson(),'Full story-set JSON copied.'));
  $('#downloadFull')?.addEventListener('click',()=>dl('bulk-story-set-prompt.json',fullJson()));
  $('#downloadZip')?.addEventListener('click',async()=>{dl(`LadyTin-${slug(current().title)}-bulk-generation-package.zip`,await makeZip(current().slides,current(),current().logo,false),'application/zip');toast('Story-set package downloaded.')});
  $('#downloadDraft')?.addEventListener('click',async()=>{dl(`LadyTin-${slug(current().title)}-incomplete-draft-package.zip`,await makeZip(current().slides,current(),current().logo,true),'application/zip');toast('Incomplete draft package downloaded.')});
  $$('[data-action]').forEach(b=>b.onclick=async()=>{const i=+b.dataset.i,s=current().slides[i],json=pretty(slidePrompt(s,i,current().slides,current(),current().logo));if(b.dataset.action==='copy')cp(json,'Slide JSON copied.');if(b.dataset.action==='json')dl(`slide-${n(i)}-prompt.json`,json);if(b.dataset.action==='validate')toast(parseJson(json).ok?'Slide JSON is valid.':'Slide JSON is invalid.',parseJson(json).ok?'ok':'bad');if(b.dataset.action==='view')$('#json-'+i).open=!$('#json-'+i).open;if(b.dataset.action==='package')dl(`LadyTin-${slug(current().title)}-slide-${n(i)}.zip`,await makeSlideZip(s,i,current().slides,current(),current().logo),'application/zip')});
}
render();
